common:
  security:
    enabled: false
  feign-oauth:
    enabled: false
  mvc:
    enabled: false
server:
  ssl:
    enabled: false
  servlet:
    context-path: /badge-system
spring:
  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 858466407850-jj0pj96ipsnl8gfmc9c262p4ecb31csm.apps.googleusercontent.com
#            client-secret: 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
    user:
      name: user
      password: 123
  application:
    name: cs544-202403-project
  datasource:
    url: jdbc:sqlserver://localhost:1434;databaseName=attendanceDB;trustServerCertificate=true
    username: sa
    password: password
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
logging:
  level:
    root: INFO
  file:
    name: /CS544/Logging/${spring.application.name}/logs
