common:
  security:
    enabled: false
  feign-oauth:
    enabled: false
  mvc:
    enabled: false
server:
  ssl:
    enabled: false
  servlet:
    context-path: /badge-system
spring:
#  activemq:
#      broker-url: http://57.151.89.65:61616
#      user: artemis
#      password: artemis
  security:
    user:
      name: user
      password: 123
  application:
    name: cs544-202403-project
  datasource:
    url: jdbc:sqlserver://localhost:1434;databaseName=project;trustServerCertificate=true
    username: sa
    password: domain
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
#
#      email:
#        queue: emailQueue
logging:
  level:
    root: INFO
  file:
    name: /CS544/Logging/${spring.application.name}/logs
