GET http://localhost:8080/badge-system/events
Authorization: Basic user 123

###
POST http://localhost:8080/badge-system/events
Authorization: Basic user 123
Content-Type: application/json

{
  "name": "EA",
  "description": "Enterprise applications"
}

###
PUT http://localhost:8080/badge-system/events/{eventId}
Authorization: Basic user 123
Content-Type: application/json

{
  "name": "New Event Name",
  "description": "New Event Description",
  "startedDateTime": "2024-03-19T09:00:00",
  "endedDateTime": "2024-03-19T18:00:00"
}


###
DELETE http://localhost:8080/badge-system/events/{eventId}
Authorization: Basic user 123
